export enum PermissionName {
  VIEW_USER = 'VIEW_USER',
  CREATE_USER = 'CREATE_USER',
  EDIT_USER = 'EDIT_USER',
  DELETE_USER = 'DELETE_USER',

  VIEW_PERMISSION = 'VIEW_PERMISSION',
  CREATE_PERMISSION = 'CREATE_PERMISSION',
  EDIT_PERMISSION = 'EDIT_PERMISSION',
  DELETE_PERMISSION = 'DELETE_PERMISSION',

  VIEW_ROLE = 'VIEW_ROLE',
  CREATE_ROLE = 'CREATE_ROLE',
  EDIT_ROLE = 'EDIT_ROLE',
  DELETE_ROLE = 'DELETE_ROLE',

  VIEW_SERVICE = 'VIEW_SERVICE',
  CREATE_SERVICE = 'CREATE_SERVICE',
  EDIT_SERVICE = 'EDIT_SERVICE',
  DELETE_SERVICE = 'DELETE_SERVICE',

  VIEW_MEDICAL_QUOTE = 'VIEW_MEDICAL_QUOTE',
  CREATE_MEDICAL_QUOTE = 'CREATE_MEDICAL_QUOTE',
  EDIT_MEDICAL_QUOTE = 'EDIT_MEDICAL_QUOTE',
  DELETE_MEDICAL_QUOTE = 'DELETE_MEDICAL_QUOTE',

  VIEW_PATIENT = 'VIEW_PATIENT',
  CREATE_PATIENT = 'CREATE_PATIENT',
  EDIT_PATIENT = 'EDIT_PATIENT',
  DELETE_PATIENT = 'DELETE_PATIENT',

  VIEW_PRICING = 'VIEW_PRICING',
  CREATE_PRICING = 'CREATE_PRICING',
  EDIT_PRICING = 'EDIT_PRICING',
  DELETE_PRICING = 'DELETE_PRICING',

  VIEW_ANALYSIS = 'VIEW_ANALYSIS',
  CREATE_ANALYSIS = 'CREATE_ANALYSIS',
  EDIT_ANALYSIS = 'EDIT_ANALYSIS',
  DELETE_ANALYSIS = 'DELETE_ANALYSIS',

  VIEW_ANALYSIS_REQUEST = 'VIEW_ANALYSIS_REQUEST',
  CREATE_ANALYSIS_REQUEST = 'CREATE_ANALYSIS_REQUEST',
  EDIT_ANALYSIS_REQUEST = 'EDIT_ANALYSIS_REQUEST',
  DELETE_ANALYSIS_REQUEST = 'DELETE_ANALYSIS_REQUEST',

  VIEW_CASHDESK = 'VIEW_CASHDESK',
  CREATE_CASHDESK = 'CREATE_CASHDESK',
  EDIT_CASHDESK = 'EDIT_CASHDESK',
  DELETE_CASHDESK = 'DELETE_CASHDESK',

  VIEW_CONSULTATION = 'VIEW_CONSULTATION',
  CREATE_CONSULTATION = 'CREATE_CONSULTATION',
  EDIT_CONSULTATION = 'EDIT_CONSULTATION',
  DELETE_CONSULTATION = 'DELETE_CONSULTATION',

  VIEW_PRACTITIONER = 'VIEW_PRACTITIONER',
  CREATE_PRACTITIONER = 'CREATE_PRACTITIONER',
  EDIT_PRACTITIONER = 'EDIT_PRACTITIONER',
  DELETE_PRACTITIONER = 'DELETE_PRACTITIONER',

  // PRESCRIPTION
  VIEW_PRESCRIPTION = 'VIEW_PRESCRIPTION',
  CREATE_PRESCRIPTION = 'CREATE_PRESCRIPTION',
  EDIT_PRESCRIPTION = 'EDIT_PRESCRIPTION',
  DELETE_PRESCRIPTION = 'DELETE_PRESCRIPTION',

  VIEW_ALLERGY_INTOLERANCE = 'VIEW_ALLERGY_INTOLERANCE',
  CREATE_ALLERGY_INTOLERANCE = 'CREATE_ALLERGY_INTOLERANCE',
  EDIT_ALLERGY_INTOLERANCE = 'EDIT_ALLERGY_INTOLERANCE',
  DELETE_ALLERGY_INTOLERANCE = 'DELETE_ALLERGY_INTOLERANCE',

  VIEW_DIAGNOSTIC_REPORTS = 'VIEW_DIAGNOSTIC_REPORTS',
  CREATE_DIAGNOSTIC_REPORTS = 'CREATE_DIAGNOSTIC_REPORTS',
  EDIT_DIAGNOSTIC_REPORTS = 'EDIT_DIAGNOSTIC_REPORTS',
  DELETE_DIAGNOSTIC_REPORTS = 'DELETE_DIAGNOSTIC_REPORTS',

  VIEW_ENCOUNTER = 'VIEW_ENCOUNTER',
  CREATE_ENCOUNTER = 'CREATE_ENCOUNTER',
  EDIT_ENCOUNTER = 'EDIT_ENCOUNTER',
  DELETE_ENCOUNTER = 'DELETE_ENCOUNTER',

  VIEW_MEDICAMENT_REQUEST = 'VIEW_MEDICAMENT_REQUEST',
  CREATE_MEDICAMENT_REQUEST = 'CREATE_MEDICAMENT_REQUEST',
  EDIT_MEDICAMENT_REQUEST = 'EDIT_MEDICAMENT_REQUEST',
  DELETE_MEDICAMENT_REQUEST = 'DELETE_MEDICAMENT_REQUEST',

  VIEW_OBSERVATION = 'VIEW_OBSERVATION',
  CREATE_OBSERVATION = 'CREATE_OBSERVATION',
  EDIT_OBSERVATION = 'EDIT_OBSERVATION',
  DELETE_OBSERVATION = 'DELETE_OBSERVATION',
}
