export enum PermissionName {
  VIEW_USER = 'VIEW_USER',
  CREATE_USER = 'CREATE_USER',
  EDIT_USER = 'EDIT_USER',
  DELETE_USER = 'DELETE_USER',

  VIEW_PERMISSION = 'VIEW_PERMISSION',
  CREATE_PERMISSION = 'CREATE_PERMISSION',
  EDIT_PERMISSION = 'EDIT_PERMISSION',
  DELETE_PERMISSION = 'DELETE_PERMISSION',

  VIEW_ROLE = 'VIEW_ROLE',
  CREATE_ROLE = 'CREATE_ROLE',
  EDIT_ROLE = 'EDIT_ROLE',
  DELETE_ROLE = 'DELETE_ROLE',

  VIEW_TOKEN_REQUEST = 'VIEW_TOKEN_REQUEST',
  CREATE_TOKEN_REQUEST = 'CREATE_TOKEN_REQUEST',
  EDIT_TOKEN_REQUEST = 'EDIT_TOKEN_REQUEST',
  DELETE_TOKEN_REQUEST = 'DELETE_TOKEN_REQUEST',

  VIEW_CONVERSATION = 'VIEW_CONVERSATION',
  CREATE_CONVERSATION = 'CREATE_CONVERSATION',
  EDIT_CONVERSATION = 'EDIT_CONVERSATION',
  DELETE_CONVERSATION = 'DELETE_CONVERSATION',

  VIEW_DIRECT_CONVERSATION = 'VIEW_DIRECT_CONVERSATION',
  CREATE_DIRECT_CONVERSATION = 'CREATE_DIRECT_CONVERSATION',
  EDIT_DIRECT_CONVERSATION = 'EDIT_DIRECT_CONVERSATION',
  DELETE_DIRECT_CONVERSATION = 'DELETE_DIRECT_CONVERSATION',

  VIEW_GROUP_CONVERSATION = 'VIEW_GROUP_CONVERSATION',
  CREATE_GROUP_CONVERSATION = 'CREATE_GROUP_CONVERSATION',
  EDIT_GROUP_CONVERSATION = 'EDIT_GROUP_CONVERSATION',
  DELETE_GROUP_CONVERSATION = 'DELETE_GROUP_CONVERSATION',

  VIEW_GROUP = 'VIEW_GROUP',
  CREATE_GROUP = 'CREATE_GROUP',
  EDIT_GROUP = 'EDIT_GROUP',
  DELETE_GROUP = 'DELETE_GROUP',
}
